### ISSUE TITLE
Make default prefix for commands more unique

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/discord-bot#36]
Currently the default prefix for commands is `?` which isn't exactly widely used among Discord bots, but also not particularly unique. I think it would be better if our default prefix is more unique, like `cw!`, to avoid clashing with prefixes used by other bots. Of course, our server does not currently intend to introduce bots other than our own CW Discord bot so there's not much practical motivation to change our prefix, but IMO doing so is still meaningful from a branding perspective. What do you think?

**Comment by kazk** [comment]
> IMO doing so is still meaningful from a branding perspective

I don't see how this will be meaningful in any way. I'd be annoyed if I was a user. Please elaborate if you have anything more specific in mind.

**If** we decide to change, how do we migrate? Start ignoring `?` prefixed messages? Start warning users about the change if they use `?`? I can't think of any reasons to justify this overhead on both sides.

We've been using `?` and users are used to it by now. I wouldn't want to change without a good reason, like migrating to the slash commands. Conflicts with other bots is not a problem currently, and I'm assuming it won't be a problem in the future either because the slash commands interface will be required for widely used bots.

**Comment by DonaldKellett** [comment]
Since the bot now advertises its help command in the status which includes the prefix, users would see the new prefix, say, `cw!`, and invoke the `cw!help` command instead which would inform the user of "new" commands starting with `cw!`, e.g. `cw!link` and `cw!rankup` instead of `?link` and `?rankup` respectively. Though I could see how existing users may have to "unlearn" the existing prefix and get used to the new one.

If we're absolutely certain that we will never use any prefix other than `?` before moving over entirely to slash commands, I guess we can close this issue and related PRs.

**Comment by DonaldKellett** [comment]
Closing since we'll be migrating to slash commands soon.
